"""Persistent dashboard activity and monitoring history."""

import sqlalchemy as sa

from alembic import op

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("chat_id", sa.BigInteger(), nullable=True),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bot_events_created_at"), "bot_events", ["created_at"], unique=False)
    op.create_index(op.f("ix_bot_events_kind"), "bot_events", ["kind"], unique=False)
    op.create_index(op.f("ix_bot_events_status"), "bot_events", ["status"], unique=False)
    op.create_index(op.f("ix_bot_events_user_id"), "bot_events", ["user_id"], unique=False)
    op.create_table(
        "poll_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(), nullable=False),
        sa.Column("provider_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column("slot_count", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["poll_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_poll_runs_job_id"), "poll_runs", ["job_id"], unique=False)
    op.create_index(op.f("ix_poll_runs_provider_id"), "poll_runs", ["provider_id"], unique=False)
    op.create_index(op.f("ix_poll_runs_started_at"), "poll_runs", ["started_at"], unique=False)
    op.create_index(op.f("ix_poll_runs_status"), "poll_runs", ["status"], unique=False)
    op.create_table(
        "poll_run_subscriptions",
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("subscription_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["poll_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("run_id", "subscription_id"),
    )
    op.create_index(
        op.f("ix_poll_run_subscriptions_user_id"),
        "poll_run_subscriptions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "provider_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("operation", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["poll_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_provider_requests_run_id"), "provider_requests", ["run_id"], unique=False
    )
    op.create_index(
        op.f("ix_provider_requests_started_at"), "provider_requests", ["started_at"], unique=False
    )
    op.create_index(
        op.f("ix_provider_requests_status"), "provider_requests", ["status"], unique=False
    )
    op.add_column("users", sa.Column("username", sa.String(), nullable=True))
    op.add_column("users", sa.Column("full_name", sa.String(), nullable=True))
    op.add_column("users", sa.Column("language_code", sa.String(), nullable=True))
    op.add_column("users", sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_users_last_seen"), "users", ["last_seen"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_last_seen"), table_name="users")
    op.drop_column("users", "last_seen")
    op.drop_column("users", "language_code")
    op.drop_column("users", "full_name")
    op.drop_column("users", "username")
    op.drop_index(op.f("ix_provider_requests_status"), table_name="provider_requests")
    op.drop_index(op.f("ix_provider_requests_started_at"), table_name="provider_requests")
    op.drop_index(op.f("ix_provider_requests_run_id"), table_name="provider_requests")
    op.drop_table("provider_requests")
    op.drop_index(op.f("ix_poll_run_subscriptions_user_id"), table_name="poll_run_subscriptions")
    op.drop_table("poll_run_subscriptions")
    op.drop_index(op.f("ix_poll_runs_status"), table_name="poll_runs")
    op.drop_index(op.f("ix_poll_runs_started_at"), table_name="poll_runs")
    op.drop_index(op.f("ix_poll_runs_provider_id"), table_name="poll_runs")
    op.drop_index(op.f("ix_poll_runs_job_id"), table_name="poll_runs")
    op.drop_table("poll_runs")
    op.drop_index(op.f("ix_bot_events_user_id"), table_name="bot_events")
    op.drop_index(op.f("ix_bot_events_status"), table_name="bot_events")
    op.drop_index(op.f("ix_bot_events_kind"), table_name="bot_events")
    op.drop_index(op.f("ix_bot_events_created_at"), table_name="bot_events")
    op.drop_table("bot_events")
    # ### end Alembic commands ###
